[package]
name = "space-lenser-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
humansize.workspace = true
jwalk.workspace = true
log.workspace = true
nix.workspace = true
rayon.workspace = true
serde.workspace = true
sysinfo.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys.workspace = true
objc2-foundation.workspace = true

[dev-dependencies]
tempfile = "3.10"
